### ISSUE TITLE
build example fail with of nightly build 20150917

### ISSUE THREAD

**Issue by avilleret** [jvcleave/ofxRPiCameraVideoGrabber#10]
I have some errors when trying to build example with the nightly build 20150917 .

~~~~
example-non-texture/src/nonTextureApp.cpp:17:19: error: invalid use of ‘enum SessionConfig::MODE’
     sessionConfig.MODE = SessionConfig::MODE_NONTEXTURE;
example-non-texture/src/nonTextureApp.cpp:66:16: error: ‘class ofxRPiCameraVideoGrabber’ has no member named ‘toggleLED’
   videoGrabber.toggleLED();
example-non-texture/src/main.cpp:8:53: error: could not convert ‘ofGLProgrammableRenderer::TYPE’ from ‘const string {aka const std::basic_string<char>}’ to ‘std::shared_ptr<ofBaseRenderer>’
  ofSetCurrentRenderer(ofGLProgrammableRenderer::TYPE);
~~~~

Here is the full log : https://gist.github.com/avilleret/93b6431f66c3ab766f4a
I'm using develop branch.

how to use this addon with latest unreleased of ?

**Comment by mirrorboy714** [comment]
The same problem occurs on my environment. But I couldn't solve it.

**Comment by jvcleave** [comment]
ofSetCurrentRenderer(ofGLProgrammableRenderer::TYPE);
is removed in OF 0.9

you have to do something like this
https://github.com/jvcleave/ofxOMXPlayer/blob/develop/example-shader/src/main.cpp
