### ISSUE TITLE
trying to compile  on a raspberry pi 2

### ISSUE THREAD

**Issue by cyrstem** [jvcleave/ofxRPiCameraVideoGrabber#13]
hello  im tryng to use this on a example i build on OF-9 
 it uses openCV 
it seem to  make it ok until i get to a error  that says 
ofxRPiVideoGrabber does not name type 
ofxRPiVideoGrabber videoGrabber;

what thats this mean  how can i fix it 
 appreciate the help

**Comment by jvcleave** [comment]
There is no such thing as ofxRPiVideoGrabber, it's either `RPiVideoGrabber` for the wrapper version or `ofxRPiCameraVideoGrabber` for the main version

**Comment by cyrstem** [comment]
thanks, but when i changed to ofxRPiCameraVideoGrabber i get the same error

**Comment by jvcleave** [comment]
Assuming you are not starting from from one of the examples, did you add `ofxRPiCameraVideoGrabber` to addons.make?

**Comment by cyrstem** [comment]
yeah  i add that line, i think i fix it, now i get  new errors so i guess im on to somethings is it better to start form the pixel example to use for something with openCV??

**Comment by jvcleave** [comment]
yeah - either that example or this addon is more setup for OpenCv
https://github.com/orgicus/ofxCvPiCam
