### ISSUE TITLE
Can't compile on RPi3 & RPI2 + lastest Raspbian + lastest OF

### ISSUE THREAD

**Issue by undessens** [jvcleave/ofxRPiCameraVideoGrabber#25]
I made a fresh SD card,  following properly the OF tutorial, ( raspbian upgraded, of9.0.3 ) then cloning the last version of the repo. The memory split is 64.
I got this message :

`
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:336: recipe for target '../../../addons/obj/linuxarmv6l/Release/ofxRPiCameraVideoGrabber/src/ofxRPiCameraVideoGrabber.o' failed
make[1]: *** [../../../addons/obj/linuxarmv6l/Release/ofxRPiCameraVideoGrabber/src/ofxRPiCameraVideoGrabber.o] Error 4
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/pi/Documents/of_0.9.3/addons/ofxRPiCameraVideoGrabber/example-demo-mode'
../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:125: recipe for target 'Release' failed
make: *** [Release] Error 2
`

**Comment by jvcleave** [comment]
are you using a -j4 switch (e.g `make -j4`)

**Comment by undessens** [comment]
yes. sudo make -j4

**Comment by jvcleave** [comment]
each job takes up memory so you are running out of ram. Try a lower number (-j2)

**Comment by undessens** [comment]
Perfect, it works. Thanks ... woaw, you are really reactive
