### ISSUE TITLE
how can i rotate the screen

### ISSUE THREAD

**Issue by rihani** [jvcleave/ofxRPiCameraVideoGrabber#28]
Hi, 

how could i rotate the screen please
thanks

**Comment by Wolftronics-SBC** [comment]
you can rotate the camera or monitor?

**Comment by jvcleave** [comment]
I think example-direct-mode-transform has this as a demo - take a look at that

https://github.com/jvcleave/ofxRPiCameraVideoGrabber/blob/master/example-direct-mode-transform/src/ofApp.cpp#L118 

I don't have the camera hooked up at the moment to try it

**Comment by rihani** [comment]
I get the following error 

```
error: base operand of ‘->’ has non-pointer type ‘ofxRPiCameraVideoGrabber’
         videoGrabber->setRotation(ROTATION_90);
```

I do insert this in keyPressed function
but don't mind setting this during setup()
```
void ofApp::keyPressed  (int key)
{
	ofLog(OF_LOG_VERBOSE, "%c keyPressed", key);

	if (key == 'e')
	{
		videoGrabber.setImageFilter(filterCollection.getNextFilter());
	}
	
	if(key == 'm')  
	{
        videoGrabber->setRotation(ROTATION_90);
	}
....
```

**Comment by jvcleave** [comment]
the error says it's not a pointer in your code, change
`videoGrabber->setRotation(ROTATION_90);`
 to 
` videoGrabber.setRotation(ROTATION_90);`

**Comment by rihani** [comment]
managed to do it using 

videoGrabber.setDisplayRotation(rotation);

thanks

**Comment by rihani** [comment]
i managed to spin the camera 180 degrees using 
`videoGrabber.setRotation(ROTATION_180);
`however how can i flip/mirror the camera vertically

**Comment by rihani** [comment]
videoGrabber.setMirror(MIRROR_VERTICAL);
