### ISSUE TITLE
Picture in picture

### ISSUE THREAD

**Issue by rihani** [jvcleave/ofxRPiCameraVideoGrabber#29]
Could you please help setup a picture in picture PIP of RPI camera, I would like to show the camera in full screen and then show a zoomed area of the camera on top of the full screen video.
Thanks

**Comment by jvcleave** [comment]
example-texture-mode somewhat does this - you will just have to scale/mask the second texture to simulate the zooming

**Comment by rihani** [comment]
thanks, i have this issue, when resizing the screen i.e. omxCameraSettings.width = 1280; //default 1280 omxCameraSettings.height = 720; to omxCameraSettings.width = 720; //default 1280
	omxCameraSettings.height = 480; //default 720, the screen goes white?
please if you may help.

**Comment by jvcleave** [comment]
typically it means you don't have enough memory assigned to the GPU. You should have at least 128MB but 256 is better.

**Comment by rihani** [comment]
thx, i narrowed it down to omxCameraSettings.enableTexture = false; . if this is false it work, also my gnu em is gpu_mem=256
