### ISSUE TITLE
ofxRPiCameraVideoGrabber + ofxOMXPlayer : conflict ?

### ISSUE THREAD

**Issue by swkzr** [jvcleave/ofxRPiCameraVideoGrabber#35]
ofxRPiCameraVideoGrabber (texture mode) does not seem to work any more if trying to use ofxOMXPlayer (texture mode) simultaneously ... camera texture is black

**Comment by jvcleave** [comment]
typically that means you are out of GPU memory

**Comment by swkzr** [comment]
That's it !
256 for GPU is ok
Thx !
