### ISSUE TITLE
ofxBaseVideoGrabber?

### ISSUE THREAD

**Issue by danomatika** [jvcleave/ofxRPiCameraVideoGrabber#7]
Could this inherit ofxBaseVideoGrabber so it's interchangeable with ofxVideoGrabber? I usually do this with cross platform apps.

Also, how do I get access to the raw pixels? Get them out of the texture?

**Comment by jvcleave** [comment]
example of a wrapper here
https://github.com/jvcleave/ofxRPiCameraVideoGrabber/tree/master/example-wrapper

texture-mode only
